spring:
  application:
    name: EduWise

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=EduWise;encrypt=true;trustServerCertificate=true
    username: sa
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true

  jackson:
    deserialization:
      fail-on-null-for-primitives: true
      fail-on-missing-creator-properties: true